import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { invokeLLM } from "./_core/llm";
import { accounts, employees, journalEntries, parties, products } from "../drizzle/schema";
import { closeCashDrawer, createAccount, updateAccount, deactivateAccount, createPartyPayment, listPartyPayments, getPartyStatement, createAttendance, createEmployee, createInvoice, createJournalEntry, createParty, createProduct, createPayrollRun, createStockMove, getDashboardSummary, listAccounts, listAttendance, listCashDrawerSessions, listEmployees, listInvoices, listJournalEntries, listNotifications, listParties, listProducts, listCurrencies, openCashDrawer, saveAttachment, updateCurrency, updateUserRole, importMasterRows } from "./db";

const accountInput = z.object({ code: z.string().min(1), name: z.string().min(2), category: z.enum(["asset", "liability", "equity", "revenue", "expense"]), parentId: z.number().optional() });
const partyInput = z.object({ type: z.enum(["customer", "supplier"]), name: z.string().min(2), phone: z.string().optional(), email: z.string().email().optional().or(z.literal("")), taxNumber: z.string().optional(), creditLimit: z.coerce.number().min(0).default(0), openingBalance: z.coerce.number().default(0), currencyCode: z.string().length(3).default("SAR") });
const productInput = z.object({ sku: z.string().min(1), barcode: z.string().optional(), name: z.string().min(2), unit: z.string().default("قطعة"), salePrice: z.coerce.number().min(0).default(0), purchasePrice: z.coerce.number().min(0).default(0), quantity: z.coerce.number().default(0), minQuantity: z.coerce.number().min(0).default(0) });
const employeeInput = z.object({ employeeNumber: z.string().min(1), name: z.string().min(2), department: z.string().optional(), phone: z.string().optional(), baseSalary: z.coerce.number().min(0).default(0), hireDate: z.coerce.date().optional() });
const invoiceInput = z.object({ invoiceNumber: z.string().min(1), type: z.enum(["sale", "purchase"]), partyId: z.number().optional(), invoiceDate: z.coerce.date(), discount: z.coerce.number().min(0).default(0), tax: z.coerce.number().min(0).default(0), paid: z.coerce.number().min(0).default(0), currencyCode: z.string().length(3).default("SAR"), exchangeRate: z.coerce.number().positive().default(1), notes: z.string().optional(), lines: z.array(z.object({ productId: z.number().optional(), description: z.string().min(1), quantity: z.coerce.number().positive(), unitPrice: z.coerce.number().min(0), taxRate: z.coerce.number().min(0).max(100).default(0) })).min(1) });
const stockMoveInput = z.object({ productId: z.number(), type: z.enum(["in", "out", "adjustment"]), quantity: z.coerce.number().positive(), reference: z.string().optional() });
const attachmentInput = z.object({ entityType: z.string().min(1), entityId: z.number(), fileName: z.string().min(1), mimeType: z.string().optional(), data: z.string().min(1) });
const attendanceInput = z.object({ employeeId: z.number(), attendanceDate: z.coerce.date(), status: z.enum(["present", "absent", "late", "leave"]), note: z.string().optional() });
const paymentInput = z.object({ partyId: z.number().int().positive(), invoiceId: z.number().int().positive().optional(), amount: z.coerce.number().positive(), paymentDate: z.coerce.date().optional(), method: z.string().min(2).default("cash"), note: z.string().optional() });

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => { ctx.res.clearCookie(COOKIE_NAME, { ...getSessionCookieOptions(ctx.req), maxAge: -1 }); return { success: true } as const; }),
  }),
  dashboard: router({ summary: protectedProcedure.query(() => getDashboardSummary()), notifications: protectedProcedure.query(() => listNotifications()) }),
  accounts: router({ list: protectedProcedure.query(() => listAccounts()), create: protectedProcedure.input(accountInput).mutation(({ input }) => createAccount(input as typeof accounts.$inferInsert)), update: adminProcedure.input(z.object({ id: z.number().int().positive(), code: z.string().min(1), name: z.string().min(2), category: z.enum(["asset", "liability", "equity", "revenue", "expense"]), parentId: z.number().int().positive().nullable().optional() })).mutation(({ input }) => updateAccount(input)), deactivate: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ input }) => deactivateAccount(input.id)) }),
  parties: router({ list: protectedProcedure.input(z.object({ type: z.enum(["customer", "supplier"]).optional() }).optional()).query(({ input }) => listParties(input?.type)), payments: protectedProcedure.input(z.object({ partyId: z.number().int().positive().optional() }).optional()).query(({ input }) => listPartyPayments(input?.partyId)), statement: protectedProcedure.input(z.object({ partyId: z.number().int().positive() })).query(({ input }) => getPartyStatement(input.partyId)), recordPayment: protectedProcedure.input(paymentInput).mutation(({ input }) => createPartyPayment({ ...input, amount: input.amount.toFixed(2), paymentDate: input.paymentDate ?? new Date() })), create: protectedProcedure.input(partyInput).mutation(({ input }) => createParty({ ...input, creditLimit: input.creditLimit.toFixed(2), openingBalance: input.openingBalance.toFixed(2) })) }),
  currencies: router({ list: protectedProcedure.query(() => listCurrencies()), updateRate: protectedProcedure.input(z.object({ code: z.string().length(3), exchangeRate: z.coerce.number().positive() })).mutation(({ input }) => updateCurrency({ code: input.code, exchangeRate: input.exchangeRate.toFixed(6) })) }),
  imports: router({ masterData: protectedProcedure.input(z.object({ accounts: z.array(z.object({ code: z.string().min(1), name: z.string().min(2), category: z.enum(["asset", "liability", "equity", "revenue", "expense"]), openingBalance: z.coerce.number().optional() })).default([]), parties: z.array(z.object({ type: z.enum(["customer", "supplier"]), name: z.string().min(2), phone: z.string().optional(), email: z.string().optional(), taxNumber: z.string().optional(), openingBalance: z.coerce.number().optional(), creditLimit: z.coerce.number().optional(), currencyCode: z.string().length(3).optional() })).default([]) })).mutation(({ input }) => importMasterRows(input)) }),
  products: router({ list: protectedProcedure.query(() => listProducts()), create: protectedProcedure.input(productInput).mutation(({ input }) => createProduct({ ...input, salePrice: input.salePrice.toFixed(2), purchasePrice: input.purchasePrice.toFixed(2), quantity: input.quantity.toFixed(3), minQuantity: input.minQuantity.toFixed(3) })) }),
  invoices: router({ list: protectedProcedure.input(z.object({ type: z.enum(["sale", "purchase"]).optional() }).optional()).query(({ input }) => listInvoices(input?.type)), create: protectedProcedure.input(invoiceInput).mutation(({ input, ctx }) => { const subtotal = input.lines.reduce((sum, line) => sum + line.quantity * line.unitPrice, 0); const tax = input.tax || input.lines.reduce((sum, line) => sum + line.quantity * line.unitPrice * line.taxRate / 100, 0); const total = Math.max(0, subtotal - input.discount + tax); const status = input.paid >= total ? "paid" : input.paid > 0 ? "partially_paid" : "issued"; return createInvoice({ invoiceNumber: input.invoiceNumber, type: input.type, partyId: input.partyId, invoiceDate: input.invoiceDate, currencyCode: input.currencyCode, exchangeRate: input.exchangeRate.toFixed(6), baseTotal: (total * input.exchangeRate).toFixed(2), subtotal: subtotal.toFixed(2), discount: input.discount.toFixed(2), tax: tax.toFixed(2), total: total.toFixed(2), paid: input.paid.toFixed(2), status, notes: input.notes }, input.lines.map(line => ({ productId: line.productId, description: line.description, quantity: line.quantity.toFixed(3), unitPrice: line.unitPrice.toFixed(2), taxRate: line.taxRate.toFixed(2), lineTotal: (line.quantity * line.unitPrice * (1 + line.taxRate / 100)).toFixed(2) }))); }) }),
  employees: router({ list: protectedProcedure.query(() => listEmployees()), create: protectedProcedure.input(employeeInput).mutation(({ input }) => createEmployee({ ...input, baseSalary: input.baseSalary.toFixed(2) })), payroll: protectedProcedure.input(z.object({ period: z.string().regex(/^\d{4}-\d{2}$/) })).mutation(({ input }) => createPayrollRun(input)), attendance: protectedProcedure.query(() => listAttendance()), recordAttendance: protectedProcedure.input(attendanceInput).mutation(({ input }) => createAttendance(input)) }),
  stock: router({ move: protectedProcedure.input(stockMoveInput).mutation(({ input }) => createStockMove({ ...input, quantity: input.quantity.toFixed(3) })) }),
  cashDrawer: router({ list: protectedProcedure.query(() => listCashDrawerSessions()), open: protectedProcedure.input(z.object({ openingAmount: z.coerce.number().min(0), notes: z.string().optional() })).mutation(({ input }) => openCashDrawer({ openingAmount: input.openingAmount.toFixed(2), notes: input.notes })), close: protectedProcedure.input(z.object({ id: z.number(), closingAmount: z.coerce.number().min(0), notes: z.string().optional() })).mutation(({ input }) => closeCashDrawer({ id: input.id, closingAmount: input.closingAmount.toFixed(2), notes: input.notes })) }),
  attachments: router({ upload: protectedProcedure.input(attachmentInput).mutation(({ input }) => saveAttachment(input)) }),
  journals: router({ list: protectedProcedure.query(() => listJournalEntries()), create: protectedProcedure.input(z.object({ entryNumber: z.string().min(1), entryDate: z.coerce.date(), description: z.string().min(2), lines: z.array(z.object({ accountId: z.number(), debit: z.coerce.number().min(0).default(0), credit: z.coerce.number().min(0).default(0), note: z.string().optional() })).min(2) })).mutation(({ input, ctx }) => createJournalEntry({ entryNumber: input.entryNumber, entryDate: input.entryDate, description: input.description, status: "posted", createdBy: ctx.user.id }, input.lines.map(line => ({ accountId: line.accountId, debit: line.debit.toFixed(2), credit: line.credit.toFixed(2), note: line.note })))) }),
  assistant: router({
    ask: protectedProcedure.input(z.object({ question: z.string().min(2), context: z.string().optional() })).mutation(async ({ input }) => {
      const response = await invokeLLM({
        model: "gpt-5-mini",
        messages: [
          { role: "system", content: "أنت مساعد محاسبي عربي دقيق. أجب بالعربية الفصحى، استخدم مصطلحات محاسبية واضحة، واذكر أن إجابتك إرشادية وليست بديلاً عن مراجعة المحاسب المعتمد. لا تخترع أرقاماً أو بيانات غير موجودة." },
          { role: "user", content: `${input.question}${input.context ? `\\nسياق النظام: ${input.context}` : ""}` },
        ],
        maxTokens: 900,
      });
      const content = response.choices[0]?.message?.content;
      return { answer: typeof content === "string" ? content : "تعذر الحصول على إجابة حالياً." };
    }),
  }),
  admin: router({ setRole: adminProcedure.input(z.object({ userId: z.number(), role: z.enum(["user", "accountant", "admin"]) })).mutation(async ({ input, ctx }) => { if (input.userId === ctx.user.id && input.role !== "admin") throw new Error("لا يمكن للمدير إلغاء صلاحية حسابه الحالي"); await updateUserRole(input.userId, input.role); return { success: true }; }) }),
});

export type AppRouter = typeof appRouter;
